language: cpp

sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install nodejs autoconf2.13 gcc-multilib g++-multilib libgtk2.0-dev libgtk-3-dev libgconf2-dev libglib2.0-dev yasm libasound2-dev libpulse-dev libx11-dev libxcb1-dev libxcb-shm0-dev libxext-dev libxt-dev libx11-xcb-dev; fi

script: ./build.sh
