language: cpp

sudo: required
dist: trusty

os:
  - linux

matrix:
  include:
  - env: ARCH="i386"
  - end: ARCH="x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install nodejs autoconf2.13 libgtk2.0-dev libgtk-3-dev libgconf2-dev libglib2.0-dev;
      sudo apt-get install yasm libasound2-dev libpulse-dev libx11-dev libxcb1-dev libxcb-shm0-dev libxext-dev libxt-dev libx11-xcb-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$ARCH" == "i386" ]]; then
          sudo apt-get install gcc-multilib g++-multilib libx11-dev:i386 libext-dev:i386;
        fi
      fi 

script: ./build.sh --arch "$ARCH"
