language: cpp
sudo: required
dist: xenial

os:
  - linux
  - osx

env:
  - ARCH="i386"
  - ARCH="x86_64"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew tap homebrew/versions;
      brew unlink node; brew unlink mercurial; brew unlink cmake;
      brew install llvm36;
      brew link llvm36;
      brew switch llvm 3.6.2;
      brew install node yasm mercurial cmake gawk ccache autoconf213;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install nodejs autoconf2.13 libgtk2.0-dev libgtk-3-dev libgconf2-dev libglib2.0-dev;
      sudo apt-get install yasm libasound2-dev libpulse-dev libx11-dev libxext-dev libxt-dev libxcb1-dev libxcb-shm0-dev libx11-xcb-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "i386" ]]; then
      sudo dpkg --add-architecture i386;
      sudo apt-get update;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$ARCH" == "i386" ]]; then
      sudo apt-get install gcc-multilib g++-multilib libx11-dev:i386 libxext-dev:i386 libxt-dev:i386 libxcb1-dev:i386 libxcb-shm0-dev:i386 libx11-xcb-dev:i386;
    fi 

script: ./build.sh --arch ${ARCH}

before_deploy:
  - mkdir -p "bin/$ARCH"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp build/libMoz2D.so "bin/$ARCH/"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp build/libMoz2D.dylib "bin/$ARCH/"; fi

deploy:
  provider: bintray
  file: "bintray.json"
  user: "syrel"
  key: ${BINTRAY_API_KEY}
