language: cpp

sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install nodejs autoconf2.13 gcc-multilib g++-multilib libgtk2.0-dev libgtk-3-dev gconf-2.0; fi

script: ./build.sh
