language: cpp, node_js

sudo: required
dist: trusty

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install autoconf2.13 gcc-multilib; fi

script: ./build.sh
